### ISSUE TITLE
holograms fall through the ground

### ISSUE THREAD

**Issue by Wqrld** [ProtocolSupport/ProtocolSupportLegacySupport#1]
holograms fall through the ground after every new load by the client, seems to be clientside. only happens for <1.8 on 1.8 servers. Using the newest holographic displays plugin. I would really want these to either never show or keep them shown to the player.  1.12.2 server

**Comment by MrPowerGamerBR** [comment]
> only happens for <1.8 on 1.8 servers

I suppose you meant "<1.8 on 1.12.2 servers", right?

**Comment by gdude2002** [comment]
> only happens for <1.8 on 1.8 servers

...

> 1.12.2 server

Which is it?

**Comment by MrPowerGamerBR** [comment]
It would also be great if you explained how to reproduce the issue, does it happen when the client unloads and then loads the chunk again?

**Comment by Wqrld** [comment]
1.12.2 server yeah, yes it happens when the client unloads and reloads the chunk. Weirdly the holograms reappear for the player after around 30 seconds

also: not related to this but to protocolsupport: 1.7 clients see other users as "Unknown" Is this a known bug?

**Comment by MrPowerGamerBR** [comment]
@Wqrld afaik it isn't known, so feel free to report it to the main ProtocolSupport repo.

Also, what clients did you test against the hologram bug? 1.4.7 up to 1.7.10 or just 1.7.X?

**Comment by Wqrld** [comment]
just 1.7 as i have a bad experience with versions older than that.
