### ISSUE TITLE
1.7.10 crash

### ISSUE THREAD

**Issue by DanielAlves123** [ProtocolSupport/ProtocolSupportLegacySupport#2]
When i try to join on 1.7.10 version i get crashed.
Logs with debug enabled: https://pastebin.com/raw/dB31cnCu
Plugin that i use: https://github.com/JitseB/npclib/

**Comment by DanielAlves123** [comment]
@Shevchik ?

**Comment by Shevchik** [comment]
Will take some time to fix.

**Comment by DanielAlves123** [comment]
@Shevchik I was using ProtocolSupportLegacyHologram and I see holograms on every version with HolographicDisplays, but when I want to use this NPCLib plugin i can't see them and with PSLS i get crashed. I tried spawning invisible horse or slime, but I didn't see their names.
