### ISSUE TITLE
Possible fix

### ISSUE THREAD

**Issue by DanielAlves123** [ProtocolSupport/ProtocolSupportLegacySupport#3]
isHologram() is returning false even when its hologram
you dont spawn hologram when creating new ArmorStandData object

**Comment by Shevchik** [comment]
Just creating armorstanddata object won't spawn hologram because you need metadata. isHologram checks if all needed meta is present. If it returns false then some meta is missing. I consider a marker meta a required meta, because otherwise nametag renders at different heights.

**Comment by DanielAlves123** [comment]
@Shevchik this check:
`isOffsetSet(((Number) armorStandData).intValue(), Constants.DW_ARMORSTANDDATA_MARKER_OFFSET)` returns false, it shouldnt
I suggest adding 1.25 to Y location
