### ISSUE TITLE
Hologram colours flushed out in 1.7?

### ISSUE THREAD

**Issue by TheFlash787** [ProtocolSupport/ProtocolSupportLegacySupport#5]
Hey! I've installed this plugin on our server **(1.7.10 -> 1.12.2)** and it appears that all of the colours from the holograms seem to have died out or there's an opacity issue?

__**Expected Result:**__
![good result](https://cdn.discordapp.com/attachments/277810482365333504/531207672049958916/unknown.png)

__**Our Result (Different hologram, but the same effect):**__
![bad result](https://cdn.discordapp.com/attachments/277810482365333504/531211420277145606/unknown.png)

**Comment by Shevchik** [comment]
There should be no blocks above hologram due to the way how they work in older versions.

**Comment by BBoyJD10** [comment]
Just put a light below it

**Comment by TheFlash787** [comment]
> Just put a light below it

Oh yeah. Like I didn't think of that! Lol.
