### ISSUE TITLE
Plugin doesn't work on 1.12.2 Spigot / Paper [Bungee]

### ISSUE THREAD

**Issue by SladeHazard** [ProtocolSupport/ProtocolSupportLegacySupport#8]
Does not work on bungee 1.12.2 spigot/paper whenever the 1.7 player joins he instantly gets kicked with this message: > [08:14:56 INFO]: Irrecoverable lost connection: Internal Exception: io.netty.handler.codec.EncoderException: MessageToMessageCodec$1 must produce at least one message. also the server has upto 20 holograms

**Comment by WesleyVanNeck** [comment]
Only latest supported

**Comment by WesleyVanNeck** [comment]
That includes also Minecraft Java versions

**Comment by SladeHazard** [comment]
I've tried everyting please help me why does this happen?????! https://www.spigotmc.org/threads/players-getting-kicked.415220/

**Comment by WesleyVanNeck** [comment]
@SladeHazard  you need latest spigot or paper
